spring.application.name=springboot_demos
spring.datasource.url=jdbc:mysql://localhost:3306/hibernatedb?createDatabaseIfNotExist=true
spring.datasource.username=rootadmin
spring.datasource.password=rootroot2510
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

